# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bsh8y/Desktop/projects/side_projects/Discord_bot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bsh8y/Desktop/projects/side_projects/Discord_bot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bsh8y/Desktop/projects/side_projects/Discord_bot/CMakeFiles /home/bsh8y/Desktop/projects/side_projects/Discord_bot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bsh8y/Desktop/projects/side_projects/Discord_bot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named antlr4cpp

# Build rule for target.
antlr4cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antlr4cpp
.PHONY : antlr4cpp

# fast build rule for target.
antlr4cpp/fast:
	$(MAKE) -f CMakeFiles/antlr4cpp.dir/build.make CMakeFiles/antlr4cpp.dir/build
.PHONY : antlr4cpp/fast

#=============================================================================
# Target rules for targets named antlr4cpp_generation_antlrcpptest

# Build rule for target.
antlr4cpp_generation_antlrcpptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antlr4cpp_generation_antlrcpptest
.PHONY : antlr4cpp_generation_antlrcpptest

# fast build rule for target.
antlr4cpp_generation_antlrcpptest/fast:
	$(MAKE) -f CMakeFiles/antlr4cpp_generation_antlrcpptest.dir/build.make CMakeFiles/antlr4cpp_generation_antlrcpptest.dir/build
.PHONY : antlr4cpp_generation_antlrcpptest/fast

#=============================================================================
# Target rules for targets named Discord_DBMS

# Build rule for target.
Discord_DBMS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Discord_DBMS
.PHONY : Discord_DBMS

# fast build rule for target.
Discord_DBMS/fast:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/build
.PHONY : Discord_DBMS/fast

#=============================================================================
# Target rules for targets named discordpp

# Build rule for target.
discordpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 discordpp
.PHONY : discordpp

# fast build rule for target.
discordpp/fast:
	$(MAKE) -f lib/discordpp/CMakeFiles/discordpp.dir/build.make lib/discordpp/CMakeFiles/discordpp.dir/build
.PHONY : discordpp/fast

#=============================================================================
# Target rules for targets named curlpp_static

# Build rule for target.
curlpp_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 curlpp_static
.PHONY : curlpp_static

# fast build rule for target.
curlpp_static/fast:
	$(MAKE) -f lib/discordpp/lib/curlpp/CMakeFiles/curlpp_static.dir/build.make lib/discordpp/lib/curlpp/CMakeFiles/curlpp_static.dir/build
.PHONY : curlpp_static/fast

#=============================================================================
# Target rules for targets named curlpp

# Build rule for target.
curlpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 curlpp
.PHONY : curlpp

# fast build rule for target.
curlpp/fast:
	$(MAKE) -f lib/discordpp/lib/curlpp/CMakeFiles/curlpp.dir/build.make lib/discordpp/lib/curlpp/CMakeFiles/curlpp.dir/build
.PHONY : curlpp/fast

lib/antlr/Table.o: lib/antlr/Table.cpp.o

.PHONY : lib/antlr/Table.o

# target to build an object file
lib/antlr/Table.cpp.o:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/Table.cpp.o
.PHONY : lib/antlr/Table.cpp.o

lib/antlr/Table.i: lib/antlr/Table.cpp.i

.PHONY : lib/antlr/Table.i

# target to preprocess a source file
lib/antlr/Table.cpp.i:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/Table.cpp.i
.PHONY : lib/antlr/Table.cpp.i

lib/antlr/Table.s: lib/antlr/Table.cpp.s

.PHONY : lib/antlr/Table.s

# target to generate assembly for a file
lib/antlr/Table.cpp.s:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/Table.cpp.s
.PHONY : lib/antlr/Table.cpp.s

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.o: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.o

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.o

# target to build an object file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.o
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.o

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.i: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.i

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.i

# target to preprocess a source file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.i
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.i

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.s: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.s

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.s

# target to generate assembly for a file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.s
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.cpp.s

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.o: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.o

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.o

# target to build an object file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.o:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.o
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.o

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.i: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.i

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.i

# target to preprocess a source file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.i:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.i
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.i

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.s: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.s

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.s

# target to generate assembly for a file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.s:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.s
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.cpp.s

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.o: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.o

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.o

# target to build an object file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.o:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.o
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.o

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.i: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.i

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.i

# target to preprocess a source file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.i:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.i
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.i

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.s: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.s

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.s

# target to generate assembly for a file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.s:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.s
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.cpp.s

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.o: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.o

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.o

# target to build an object file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.o
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.o

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.i: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.i

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.i

# target to preprocess a source file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.i
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.i

lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.s: lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.s

.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.s

# target to generate assembly for a file
lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.s
.PHONY : lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.cpp.s

lib/antlr/db_engine.o: lib/antlr/db_engine.cpp.o

.PHONY : lib/antlr/db_engine.o

# target to build an object file
lib/antlr/db_engine.cpp.o:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/db_engine.cpp.o
.PHONY : lib/antlr/db_engine.cpp.o

lib/antlr/db_engine.i: lib/antlr/db_engine.cpp.i

.PHONY : lib/antlr/db_engine.i

# target to preprocess a source file
lib/antlr/db_engine.cpp.i:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/db_engine.cpp.i
.PHONY : lib/antlr/db_engine.cpp.i

lib/antlr/db_engine.s: lib/antlr/db_engine.cpp.s

.PHONY : lib/antlr/db_engine.s

# target to generate assembly for a file
lib/antlr/db_engine.cpp.s:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/db_engine.cpp.s
.PHONY : lib/antlr/db_engine.cpp.s

lib/antlr/parseTreeVisitor.o: lib/antlr/parseTreeVisitor.cpp.o

.PHONY : lib/antlr/parseTreeVisitor.o

# target to build an object file
lib/antlr/parseTreeVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/parseTreeVisitor.cpp.o
.PHONY : lib/antlr/parseTreeVisitor.cpp.o

lib/antlr/parseTreeVisitor.i: lib/antlr/parseTreeVisitor.cpp.i

.PHONY : lib/antlr/parseTreeVisitor.i

# target to preprocess a source file
lib/antlr/parseTreeVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/parseTreeVisitor.cpp.i
.PHONY : lib/antlr/parseTreeVisitor.cpp.i

lib/antlr/parseTreeVisitor.s: lib/antlr/parseTreeVisitor.cpp.s

.PHONY : lib/antlr/parseTreeVisitor.s

# target to generate assembly for a file
lib/antlr/parseTreeVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/lib/antlr/parseTreeVisitor.cpp.s
.PHONY : lib/antlr/parseTreeVisitor.cpp.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/Discord_DBMS.dir/build.make CMakeFiles/Discord_DBMS.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... antlr4cpp"
	@echo "... rebuild_cache"
	@echo "... antlr4cpp_generation_antlrcpptest"
	@echo "... Discord_DBMS"
	@echo "... edit_cache"
	@echo "... discordpp"
	@echo "... curlpp_static"
	@echo "... curlpp"
	@echo "... lib/antlr/Table.o"
	@echo "... lib/antlr/Table.i"
	@echo "... lib/antlr/Table.s"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.o"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.i"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlBaseVisitor.s"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.o"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.i"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlLexer.s"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.o"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.i"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlParser.s"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.o"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.i"
	@echo "... lib/antlr/antlr4cpp_generated_src/antlrcpptest/dmlVisitor.s"
	@echo "... lib/antlr/db_engine.o"
	@echo "... lib/antlr/db_engine.i"
	@echo "... lib/antlr/db_engine.s"
	@echo "... lib/antlr/parseTreeVisitor.o"
	@echo "... lib/antlr/parseTreeVisitor.i"
	@echo "... lib/antlr/parseTreeVisitor.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

